[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.13"
optimizer = true
optimizer_runs = 200
via_ir = false

# RPC endpoints
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# Etherscan API key for contract verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
